# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

# trigger:
#   none

pr:
  branches:
    include:
    - main
  paths:
    include:
    - tutorials/Flags/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'vysnu96/flag-quiz-without-db'
        command: 'buildAndPush'
        dockerfile: '$(Build.SourcesDirectory)/tutorials/Flags/Dockerfile'
        tags: |
          $(tag)
