name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'tutorials/Flags/**'

jobs:
  flags:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'tutorials/Flags/')
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file tutorials/Flags/Dockerfile --tag ghcr.io/vysnu96/flagquiz:${{ github.run_number }}

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push Docker Image to GHCR
      run: docker push ghcr.io/vysnu96/flagquiz:${{ github.run_number }}
